# Generated by Django 4.1.3 on 2022-11-05 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_state', models.CharField(max_length=9)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.IntegerField()),
                ('o_plyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_games_as_o', to=settings.AUTH_USER_MODEL)),
                ('x_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(max_length=9)),
                ('is_x_move', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_move_date', models.DateTimeField(null=True)),
                ('o_plyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_o', to=settings.AUTH_USER_MODEL)),
                ('x_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
