# Generated by Django 4.1.3 on 2022-11-05 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_game_current_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='o_plyer',
            new_name='o_player',
        ),
        migrations.CreateModel(
            name='PlayerAwaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awaiting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_from_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamehistory')),
            ],
        ),
    ]
