# Generated by Django 4.1.3 on 2022-11-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_o_plyer_game_o_player_playerawaiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='o_plyer',
            new_name='o_player',
        ),
    ]
