version: "3.9"
services:
  frontend:
    container_name: tictactoe_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  backend:
    container_name: tictactoe_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#  db:
#    container_name: tictactoe_db
#    image: postgres:12.0-alpine
#    env_file: ./backend/backend/.env
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#volumes:
#  postgres_data:
    